export const PRESETS = [
  {
    name: "Cassette Tape",
    smooth: true,  radio: false,
    bitDepth: 16,  rate: 14,
    chaos: 0.05,   drive: 1.5,   mix: 0.75,
    interval: 2,   intervalMs: 800,
  },
  {
    name: "Warm Vinyl",
    smooth: true,  radio: false,
    bitDepth: 20,  rate: 20,
    chaos: 0.0,    drive: 1.2,   mix: 0.60,
    interval: 2,   intervalMs: 2000,
  },
  {
    name: "VHS Warble",
    smooth: true,  radio: true,
    bitDepth: 14,  rate: 19,
    chaos: 0.18,   drive: 2.0,   mix: 0.70,
    interval: 2,   intervalMs: 1200,
  },
  {
    name: "Lo-Fi Bedroom",
    smooth: true,  radio: false,
    bitDepth: 12,  rate: 11,
    chaos: 0.08,   drive: 2.5,   mix: 0.80,
    interval: 2,   intervalMs: 600,
  },
  {
    name: "Telephone",
    smooth: false, radio: true,
    bitDepth: 8,   rate: 5,
    chaos: 0.30,   drive: 3.5,   mix: 0.80,
    interval: 2,   intervalMs: 400,
  },
  {
    name: "Distant Station",
    smooth: false, radio: true,
    bitDepth: 10,  rate: 16,
    chaos: 0.55,   drive: 2.5,   mix: 0.85,
    interval: 2,   intervalMs: 600,
  },
  {
    name: "8-Bit Arcade",
    smooth: false, radio: false,
    bitDepth: 4,   rate: 11,
    chaos: 0.0,    drive: 2.0,   mix: 1.0,
    interval: 2,   intervalMs: 500,
  },
  {
    name: "Digital Glitch",
    smooth: false, radio: false,
    bitDepth: 6,   rate: 8,
    chaos: 0.15,   drive: 3.0,   mix: 0.90,
    interval: 2,   intervalMs: 250,
  },
  {
    name: "Stutter God",
    smooth: false, radio: true,
    bitDepth: 10,  rate: 16,
    chaos: 0.78,   drive: 4.0,   mix: 0.95,
    interval: 2,   intervalMs: 150,
  },
  {
    name: "Signal Lost",
    smooth: false, radio: true,
    bitDepth: 3,   rate: 3,
    chaos: 0.90,   drive: 7.0,   mix: 1.0,
    interval: 2,   intervalMs: 80,
  },
];
