#pragma once
#include <juce_core/juce_core.h>

class LicenseValidator
{
public:
    struct License {
        bool         valid = false;
        juce::String email;
    };

    static License      validate(const juce::String& key);
    static License      checkSaved();
    static void         saveKey(const juce::String& key);

private:
    // Public key generated by scripts/keygen.py — keep the private key secret.
    static constexpr const char* PUBLIC_KEY =
        "10001,77c4c79700948b9ee75eb4acda81f1652c3f0aecb740a9e19e49993c39af9a6"
        "a39789c98ae159cd04f11597c5116c4238026194da6c93c6595c06766d72afff6"
        "f34e758950c05a9e85e9b55b5424ec8c853c758fea2ceb572999ae012f9ef0bd0"
        "6dc40f789e31679b7d6906b31e6ddb205e2e121e6d98bacf5c6b0ed92cadf9f";

    static bool verifySignature(const juce::String& data, const juce::String& sigHex);
};
