#!/usr/bin/env python3
"""
Issue a license key for a customer.

Usage:
  python3 scripts/sign_license.py customer@example.com

The output string is the license key to send to the customer.
They paste it into the plugin's activation overlay.
"""
import hashlib
import base64
import sys

# Private key generated by keygen.py — NEVER commit this to a public repo.
PRIVATE_KEY = (
    "eee3f1b79fd0ab2d29121e0f294846d6268b189f50660a739be5f15fcf3014300cb226a7e393f8550"
    "760f3bca3816577ea0414346e98b57f6a537bec05021fc915abb70714f927f420bcc8e9a14b5e5775"
    "fca3337ed0971b859cfce3d1b3bbd75fe20d150517cd914ad0050e4fb7488710fca91d8ed5e16bb4a"
    "48d27d50d5b1,"
    "77c4c79700948b9ee75eb4acda81f1652c3f0aecb740a9e19e49993c39af9a6a39789c98ae159cd04"
    "f11597c5116c4238026194da6c93c6595c06766d72afff6f34e758950c05a9e85e9b55b5424ec8c85"
    "3c758fea2ceb572999ae012f9ef0bd06dc40f789e31679b7d6906b31e6ddb205e2e121e6d98bacf5c"
    "6b0ed92cadf9f"
)


def parse_key(s: str):
    e_hex, n_hex = s.split(",")
    return int(e_hex, 16), int(n_hex, 16)


def sign_license(email: str, product: str = "Degradizer") -> str:
    data = f"email={email};product={product}"
    hash_bytes = hashlib.sha256(data.encode("utf-8")).digest()
    # JUCE BigInteger::loadFromMemoryBlock treats byte 0 as the LSB.
    hash_int = int.from_bytes(hash_bytes, "little")
    d, n = parse_key(PRIVATE_KEY)
    sig = pow(hash_int, d, n)
    b64 = base64.b64encode(data.encode("utf-8")).decode("ascii")
    return f"{b64}:{hex(sig)[2:]}"


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <customer-email>", file=sys.stderr)
        sys.exit(1)
    email = sys.argv[1]
    print(sign_license(email))
